using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using System.Xml.XPath;
using FluentAssertions;
using Melville.Fonts.SfntParsers.TableDeclarations.CffGlyphs;
using Melville.Parsing.MultiplexSources;
using Xunit;

namespace Melville.Pdf.DataModelTests.Fonts.Type1Text;

public class ReadStandardEncoding
{
    private static CffGenericFont FontWithEncodingOffset(long offset) =>
        new(MultiplexSourceFactory.Create([]),
            1000, "Fake Font", 0, 0, 0, 0, null!, 0, offset);

}

public class ReadStandardCharSets
{
    [Fact]
    public async Task IsoAdobeCharset()
    {
        var sut = FontWithCharsetOffset(0);
        var result = await sut.GlyphNamesAsync();

        result.Should().BeEquivalentTo(Extract("""
            .notdef
            space
            exclam
            quotedbl
            numbersign
            dollar
            percent
            ampersand
            quoteright
            parenleft
            parenright
            asterisk
            plus
            comma
            hyphen
            period
            slash
            zero
            one
            two
            three
            four
            five
            six
            seven
            eight
            nine
            colon
            semicolon
            less
            equal
            greater
            question
            at
            A
            B
            C
            D
            E
            F
            G
            H
            I
            J
            K
            L
            M
            N
            O
            P
            Q
            R
            S
            T
            U
            V
            W
            X
            Y
            Z
            bracketleft
            backslash
            bracketright
            asciicircum
            underscore
            quoteleft
            a
            b
            c
            d
            e
            f
            g
            h
            i
            j
            k
            l
            m
            n
            o
            p
            q
            r
            s
            t
            u
            v
            w
            x
            y
            z
            braceleft
            bar
            braceright
            asciitilde
            exclamdown
            cent
            sterling
            fraction
            yen
            florin
            section
            currency
            quotesingle
            quotedblleft
            guillemotleft
            guilsinglleft
            guilsinglright
            fi
            fl
            endash
            dagger
            daggerdbl
            periodcentered
            paragraph
            bullet
            quotesinglbase
            quotedblbase
            quotedblright
            guillemotright
            ellipsis
            perthousand
            questiondown
            grave
            acute
            circumflex
            tilde
            macron
            breve
            dotaccent
            dieresis
            ring
            cedilla
            hungarumlaut
            ogonek
            caron
            emdash
            AE
            ordfeminine
            Lslash
            Oslash
            OE
            ordmasculine
            ae
            dotlessi
            lslash
            oslash
            oe
            germandbls
            onesuperior
            logicalnot
            mu
            trademark
            Eth
            onehalf
            plusminus
            Thorn
            onequarter
            divide
            brokenbar
            degree
            thorn
            threequarters
            twosuperior
            registered
            minus
            eth
            multiply
            threesuperior
            copyright
            Aacute
            Acircumflex
            Adieresis
            Agrave
            Aring
            Atilde
            Ccedilla
            Eacute
            Ecircumflex
            Edieresis
            Egrave
            Iacute
            Icircumflex
            Idieresis
            Igrave
            Ntilde
            Oacute
            Ocircumflex
            Odieresis
            Ograve
            Otilde
            Scaron
            Uacute
            Ucircumflex
            Udieresis
            Ugrave
            Yacute
            Ydieresis
            Zcaron
            aacute
            acircumflex
            adieresis
            agrave
            aring
            atilde
            ccedilla
            eacute
            ecircumflex
            edieresis
            egrave
            iacute
            icircumflex
            idieresis
            igrave
            ntilde
            oacute
            ocircumflex
            odieresis
            ograve
            otilde
            scaron
            uacute
            ucircumflex
            udieresis
            ugrave
            yacute
            ydieresis
            zcaron
            """));
    }

    private IEnumerable<string> Extract(string s) => 
        s.Split("\r\n", StringSplitOptions.RemoveEmptyEntries);

    private static CffGenericFont FontWithCharsetOffset(long offset) =>
        new(MultiplexSourceFactory.Create([]),
            1000, "Fake Font", 0, 0, 0, 0, null!, offset, 0);

    [Fact]
    public async Task ExpertCharset()
    {
        var sut = FontWithCharsetOffset(1);
        var result = await sut.GlyphNamesAsync();
        result.Should().BeEquivalentTo(Extract("""
            .notdef
            space
            exclamsmall
            Hungarumlautsmall
            dollaroldstyle
            dollarsuperior
            ampersandsmall
            Acutesmall
            parenleftsuperior
            parenrightsuperior
            twodotenleader
            onedotenleader
            comma
            hyphen
            period
            fraction
            zerooldstyle
            oneoldstyle
            twooldstyle
            threeoldstyle
            fouroldstyle
            fiveoldstyle
            sixoldstyle
            sevenoldstyle
            eightoldstyle
            nineoldstyle
            colon
            semicolon
            commasuperior
            threequartersemdash
            periodsuperior
            questionsmall
            asuperior
            bsuperior
            centsuperior
            dsuperior
            esuperior
            isuperior
            lsuperior
            msuperior
            nsuperior
            osuperior
            rsuperior
            ssuperior
            tsuperior
            ff
            fi
            fl
            ffi
            ffl
            parenleftinferior
            parenrightinferior
            Circumflexsmall
            hyphensuperior
            Gravesmall
            Asmall
            Bsmall
            Csmall
            Dsmall
            Esmall
            Fsmall
            Gsmall
            Hsmall
            Ismall
            Jsmall
            Ksmall
            Lsmall
            Msmall
            Nsmall
            Osmall
            Psmall
            Qsmall
            Rsmall
            Ssmall
            Tsmall
            Usmall
            Vsmall
            Wsmall
            Xsmall
            Ysmall
            Zsmall
            colonmonetary
            onefitted
            rupiah
            Tildesmall
            exclamdownsmall
            centoldstyle
            Lslashsmall
            Scaronsmall
            Zcaronsmall
            Dieresissmall
            Brevesmall
            Caronsmall
            Dotaccentsmall
            Macronsmall
            figuredash
            hypheninferior
            Ogoneksmall
            Ringsmall
            Cedillasmall
            onequarter
            onehalf
            threequarters
            questiondownsmall
            oneeighth
            threeeighths
            fiveeighths
            seveneighths
            onethird
            twothirds
            zerosuperior
            onesuperior
            twosuperior
            threesuperior
            foursuperior
            fivesuperior
            sixsuperior
            sevensuperior
            eightsuperior
            ninesuperior
            zeroinferior
            oneinferior
            twoinferior
            threeinferior
            fourinferior
            fiveinferior
            sixinferior
            seveninferior
            eightinferior
            nineinferior
            centinferior
            dollarinferior
            periodinferior
            commainferior
            Agravesmall
            Aacutesmall
            Acircumflexsmall
            Atildesmall
            Adieresissmall
            Aringsmall
            AEsmall
            Ccedillasmall
            Egravesmall
            Eacutesmall
            Ecircumflexsmall
            Edieresissmall
            Igravesmall
            Iacutesmall
            Icircumflexsmall
            Idieresissmall
            Ethsmall
            Ntildesmall
            Ogravesmall
            Oacutesmall
            Ocircumflexsmall
            Otildesmall
            Odieresissmall
            OEsmall
            Oslashsmall
            Ugravesmall
            Uacutesmall
            Ucircumflexsmall
            Udieresissmall
            Yacutesmall
            Thornsmall
            Ydieresissmall
            """));
    }
    [Fact]
    public async Task ExpertSubsetCharset()
    {
        var sut = FontWithCharsetOffset(2);
        var result = await sut.GlyphNamesAsync();
        var expectation = Extract("""
            .notdef
            space
            dollaroldstyle
            dollarsuperior
            parenleftsuperior
            parenrightsuperior
            twodotenleader
            onedotenleader
            comma
            hyphen
            period
            fraction
            zerooldstyle
            oneoldstyle
            twooldstyle
            threeoldstyle
            fouroldstyle
            fiveoldstyle
            sixoldstyle
            sevenoldstyle
            eightoldstyle
            nineoldstyle
            colon
            semicolon
            commasuperior
            threequartersemdash
            periodsuperior
            asuperior
            bsuperior
            centsuperior
            dsuperior
            esuperior
            isuperior
            lsuperior
            msuperior
            nsuperior
            osuperior
            rsuperior
            ssuperior
            tsuperior
            ff
            fi
            fl
            ffi
            ffl
            parenleftinferior
            parenrightinferior
            hyphensuperior
            colonmonetary
            onefitted
            rupiah
            centoldstyle
            figuredash
            hypheninferior
            onequarter
            onehalf
            threequarters
            oneeighth
            threeeighths
            fiveeighths
            seveneighths
            onethird
            twothirds
            zerosuperior
            onesuperior
            twosuperior
            threesuperior
            foursuperior
            fivesuperior
            sixsuperior
            sevensuperior
            eightsuperior
            ninesuperior
            zeroinferior
            oneinferior
            twoinferior
            threeinferior
            fourinferior
            fiveinferior
            sixinferior
            seveninferior
            eightinferior
            nineinferior
            centinferior
            dollarinferior
            periodinferior
            commainferior
            """);
        result.Should().BeEquivalentTo(expectation);
    }
}