using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.CSharp.Syntax;

namespace Melville.Fonts.TableGenerator
{
    public readonly partial struct CodeGenerator
    {
        private readonly ISymbol classSymbol;
        private readonly MemberGenerator[] fields;
        private readonly StringBuilder output = new();

        public CodeGenerator(ISymbol classSymbol, IEnumerable<GeneratorAttributeSyntaxContext> fields)
        {
            this.classSymbol = classSymbol;
            this.fields = fields.Select(MemberGeneratorFactory.Create).ToArray();
        }


        public string CreateCode()
        {
            WritePrefix();
            GenerateReaderConstructor();
            output.AppendLine();
            GenerateLoadAsyncMethod();
            output.AppendLine();
            GenerateSizeMember();
            GenerateLoadStatic();
            WriteSuffix();
            return output.ToString();
        }

        private void GenerateLoadStatic()
        {
            output.AppendLine($"""
                public static global::{classSymbol} LoadStatic(
                    ref global::System.Buffers.SequenceReader<byte> reader)=> new(ref reader);  
            """);
        }

        private void GenerateLoadAsyncMethod()
        {

            output.AppendLine("""
                    public async global::System.Threading.Tasks.ValueTask LoadAsync(
                        global::System.IO.Pipelines.PipeReader reader)
                    {
                """);
            foreach (var item in fields)
            {
                item.LoadArrayLine(output);
            }
            output.AppendLine("    }");
        }

        private void GenerateReaderConstructor()
        {
            output.AppendLine(
                $"    public {ClassSyntax().Identifier} (ref global::System.Buffers.SequenceReader<byte> reader)");
            output.AppendLine("    {");
            foreach (var item in fields)
            {
                item.ConstructorLine(output);
            }
            output.AppendLine("    }");
        }

        private void GenerateSizeMember() => 
            output.AppendLine($"    public static int  StaticSize => {ComputeStaticSize()};");

        private string ComputeStaticSize() => fields.Select(ComputeSizeFor).Sum().ToString();

        private static int ComputeSizeFor(MemberGenerator memberGenerator)
        {
            if (memberGenerator.IsArray) return 0;
            return memberGenerator.TypeName() switch
            {
                "uint" => 4,
                "int" => 4,
                "ushort" => 2,
                "short" => 2,
                var x => throw new NotImplementedException($"cannot size type {x}")
            };
        }

        private void WritePrefix()
        {
            var tds = ClassSyntax();
            output.AppendLine($$"""
                // Implementation for PostscriptOperatorCollection names {{classSymbol.Name}}
                // this file was auto-generated by Melville.Fonts.TableGenerator
                using Melville.Parsing.AwaitConfiguration;
                namespace {{classSymbol.ContainingNamespace}};

                {{$"{tds.Modifiers} {tds.Keyword} {tds.Identifier}"}}: 
                    Melville.Fonts.SfntParsers.TableParserParts.IGeneratedParsable<global::{{classSymbol}}>
                {
                """);
        }
        
        private TypeDeclarationSyntax ClassSyntax() => 
            (TypeDeclarationSyntax)classSymbol.DeclaringSyntaxReferences[0].GetSyntax();

        private void WriteSuffix() => output.AppendLine("}");
    }
}