using System;

namespace Melville.Pdf.LowLevel.Writers.ContentStreams;

/// <summary>
/// This is a struct that is used in the ContentStreamWriter to represent operators
/// with paired begin/end operators.  Consumers can put the opening operator creation in
/// a using statement, and the appropriate closing operators will be generated by the structure
/// of the C# code.  This is a struct that incidentally implements an interface, but the compiler
/// is bright enough to not box this span on the dispose call.
/// </summary>
public unsafe struct DeferedClosingTask : IDisposable
{
    private readonly ContentStreamPipeWriter writer;
    private fixed byte closingOperator[4];
    private readonly int closingOperatorLength;
    private Span<byte> ClosingOperatorSpan(byte* basePtr) => 
        new(basePtr, Math.Min(4, closingOperatorLength));

    internal DeferedClosingTask(ContentStreamPipeWriter writer, in ReadOnlySpan<byte> closingOperator)
    {
        this.writer = writer;
        closingOperatorLength = closingOperator.Length;
        fixed (byte* opPtr = this.closingOperator)
        {
            closingOperator.CopyTo(ClosingOperatorSpan(opPtr));
        }
    }

    /// <summary>
    /// Writes out the closing operator for this block
    /// </summary>
    public void Dispose()
    {
        fixed (byte* opPtr = closingOperator)
        {
            writer.WriteOperator(ClosingOperatorSpan(opPtr));
        }
    }
}